# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2.1
workflows:
  version: 2.1
  test:
    jobs:
      - test:
          matrix:
            parameters:
              python_version: ["2.7", "3.5"]
              debian_version: ["stretch"]

jobs:
  test:
    parameters:
      python_version:
        type: string
      debian_version:
        type: string
    docker:
      # specify the version you desire here
      - image: circleci/python:<< parameters.python_version >>-<< parameters.debian_version >>
    working_directory: ~/repo<< parameters.python_version >>

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - test-<< parameters.python_version >>-{{ checksum "requirements/test.txt" }}
          # fallback to using the latest cache if no exact match is found
          - test-<< parameters.python_version >>-

      - run:
          name: activate virtualenv and install dependencies.
          command: |
            test -d venv || virtualenv ./venv
            . venv/bin/activate
            make test_requirements

      - save_cache:
          paths:
            - ./venv
          key: test-<< parameters.python_version >>-{{ checksum "requirements/test.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            coverage run --source="." manage.py test
            coverage report --fail-under=71 -m
            pycodestyle ./eox_tagging
            pylint ./eox_tagging --rcfile=./setup.cfg
            isort --check-only --recursive --diff ./eox_tagging
